### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by adamslaski** [nilskp/jmh-charts#7]
Hi Nils,
Would you mind me forking jmh-charts and modifying it for my purposes? Repo doesn't have a license, so I prefer to check. A really cool stuff btw.

BR,
Adam

**Comment by nilskp** [comment]
I've added MIT license.
If it's incremental changes, and bug fixes, you may want to be a contributor instead. This would help existing users.
But regardless, feel free to fork.

**Comment by adamslaski** [comment]
Many thanks!
My use case is slightly different. With line chart and a wizard for setting
up charts. Please, find it here:
https://bitbucket.org/adasla/jmh-charts-with-creator

BR,
Adam

On 16 February 2018 at 17:47, Nils Kilden-Pedersen <notifications@github.com
